//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.04.14 at 10:54:35 PM CEST 
//


package aufgabe4;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for unitIngredient.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="unitIngredient">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="Msp."/>
 *     &lt;enumeration value="cm"/>
 *     &lt;enumeration value="mg"/>
 *     &lt;enumeration value="g"/>
 *     &lt;enumeration value="dg"/>
 *     &lt;enumeration value="kg"/>
 *     &lt;enumeration value="cl"/>
 *     &lt;enumeration value="ml"/>
 *     &lt;enumeration value="dl"/>
 *     &lt;enumeration value="EL"/>
 *     &lt;enumeration value="EL, gest."/>
 *     &lt;enumeration value="TL"/>
 *     &lt;enumeration value="TL, gest."/>
 *     &lt;enumeration value="Pkt."/>
 *     &lt;enumeration value="n.B."/>
 *     &lt;enumeration value="e. Stiele"/>
 *     &lt;enumeration value="evt."/>
 *     &lt;enumeration value="gr. Dose"/>
 *     &lt;enumeration value="gr. Fl."/>
 *     &lt;enumeration value="kl. Dose"/>
 *     &lt;enumeration value="Port"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "unitIngredient")
@XmlEnum
public enum UnitIngredient {

    @XmlEnumValue("Msp.")
    MSP("Msp."),
    @XmlEnumValue("cm")
    CM("cm"),
    @XmlEnumValue("mg")
    MG("mg"),
    @XmlEnumValue("g")
    G("g"),
    @XmlEnumValue("dg")
    DG("dg"),
    @XmlEnumValue("kg")
    KG("kg"),
    @XmlEnumValue("cl")
    CL("cl"),
    @XmlEnumValue("ml")
    ML("ml"),
    @XmlEnumValue("dl")
    DL("dl"),
    EL("EL"),
    @XmlEnumValue("EL, gest.")
    EL_GEST("EL, gest."),
    TL("TL"),
    @XmlEnumValue("TL, gest.")
    TL_GEST("TL, gest."),
    @XmlEnumValue("Pkt.")
    PKT("Pkt."),
    @XmlEnumValue("n.B.")
    N_B("n.B."),
    @XmlEnumValue("e. Stiele")
    E_STIELE("e. Stiele"),
    @XmlEnumValue("evt.")
    EVT("evt."),
    @XmlEnumValue("gr. Dose")
    GR_DOSE("gr. Dose"),
    @XmlEnumValue("gr. Fl.")
    GR_FL("gr. Fl."),
    @XmlEnumValue("kl. Dose")
    KL_DOSE("kl. Dose"),
    @XmlEnumValue("Port")
    PORT("Port");
    private final String value;

    UnitIngredient(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static UnitIngredient fromValue(String v) {
        for (UnitIngredient c: UnitIngredient.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
